//! Target Capabilities system.

use crate::target::{Architecture, TargetFeature, TargetFeatures};

/// Complete capabilities flags for a target backend.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TargetCapabilities {
    pub supports_threads: bool,
    pub supports_tls: bool,
    pub supports_exceptions: bool,
    pub supports_unwind: bool,
    pub supports_simd: bool,
    pub supports_vector: bool,
    pub supports_atomics: bool,
    pub supports_fpu: bool,
    pub supports_dynamic_linking: bool,
    pub supports_static_linking: bool,
    pub supports_shared_libraries: bool,
    pub supports_jit: bool,
    pub supports_aot: bool,
    pub supports_gc: bool,
    pub supports_virtual_memory: bool,
    pub supports_gpu_offload: bool,
    pub supports_async: bool,
    pub supports_debug_info: bool,
    pub features: TargetFeatures,
}

impl Default for TargetCapabilities {
    fn default() -> Self {
        Self::for_architecture(&Architecture::X86_64)
    }
}

impl TargetCapabilities {
    pub fn for_architecture(arch: &Architecture) -> Self {
        match arch {
            Architecture::X86_64 => Self {
                supports_threads: true,
                supports_tls: true,
                supports_exceptions: true,
                supports_unwind: true,
                supports_simd: true,
                supports_vector: true,
                supports_atomics: true,
                supports_fpu: true,
                supports_dynamic_linking: true,
                supports_static_linking: true,
                supports_shared_libraries: true,
                supports_jit: true,
                supports_aot: true,
                supports_gc: true,
                supports_virtual_memory: true,
                supports_gpu_offload: true,
                supports_async: true,
                supports_debug_info: true,
                features: TargetFeatures {
                    features: vec![
                        TargetFeature::new("sse", true),
                        TargetFeature::new("sse2", true),
                        TargetFeature::new("sse3", true),
                        TargetFeature::new("ssse3", true),
                        TargetFeature::new("sse4.1", true),
                        TargetFeature::new("sse4.2", true),
                        TargetFeature::new("avx", true),
                        TargetFeature::new("avx2", true),
                        TargetFeature::new("bmi1", true),
                        TargetFeature::new("bmi2", true),
                        TargetFeature::new("fma", true),
                        TargetFeature::new("atomics", true),
                    ],
                },
            },
            Architecture::AArch64 => Self {
                supports_threads: true,
                supports_tls: true,
                supports_exceptions: true,
                supports_unwind: true,
                supports_simd: true,
                supports_vector: true,
                supports_atomics: true,
                supports_fpu: true,
                supports_dynamic_linking: true,
                supports_static_linking: true,
                supports_shared_libraries: true,
                supports_jit: true,
                supports_aot: true,
                supports_gc: true,
                supports_virtual_memory: true,
                supports_gpu_offload: true,
                supports_async: true,
                supports_debug_info: true,
                features: TargetFeatures {
                    features: vec![
                        TargetFeature::new("neon", true),
                        TargetFeature::new("fp16", true),
                        TargetFeature::new("atomics", true),
                        TargetFeature::new("crypto", true),
                    ],
                },
            },
            Architecture::RiscV64 => Self {
                supports_threads: true,
                supports_tls: true,
                supports_exceptions: true,
                supports_unwind: true,
                supports_simd: false,
                supports_vector: true,
                supports_atomics: true,
                supports_fpu: true,
                supports_dynamic_linking: true,
                supports_static_linking: true,
                supports_shared_libraries: true,
                supports_jit: true,
                supports_aot: true,
                supports_gc: true,
                supports_virtual_memory: true,
                supports_gpu_offload: false,
                supports_async: true,
                supports_debug_info: true,
                features: TargetFeatures {
                    features: vec![
                        TargetFeature::new("i", true),
                        TargetFeature::new("m", true),
                        TargetFeature::new("a", true),
                        TargetFeature::new("f", true),
                        TargetFeature::new("d", true),
                        TargetFeature::new("c", true),
                        TargetFeature::new("v", false),
                    ],
                },
            },
            Architecture::Wasm32 | Architecture::Wasm64 => Self {
                supports_threads: false,
                supports_tls: false,
                supports_exceptions: true,
                supports_unwind: false,
                supports_simd: true,
                supports_vector: false,
                supports_atomics: false,
                supports_fpu: true,
                supports_dynamic_linking: false,
                supports_static_linking: true,
                supports_shared_libraries: false,
                supports_jit: false,
                supports_aot: true,
                supports_gc: true,
                supports_virtual_memory: false,
                supports_gpu_offload: false,
                supports_async: true,
                supports_debug_info: true,
                features: TargetFeatures::new(),
            },
            Architecture::Embedded(_) => Self {
                supports_threads: false,
                supports_tls: false,
                supports_exceptions: false,
                supports_unwind: false,
                supports_simd: false,
                supports_vector: false,
                supports_atomics: true,
                supports_fpu: false,
                supports_dynamic_linking: false,
                supports_static_linking: true,
                supports_shared_libraries: false,
                supports_jit: false,
                supports_aot: true,
                supports_gc: false,
                supports_virtual_memory: false,
                supports_gpu_offload: false,
                supports_async: false,
                supports_debug_info: true,
                features: TargetFeatures::new(),
            },
            Architecture::Gpu(_) => Self {
                supports_threads: true,
                supports_tls: false,
                supports_exceptions: false,
                supports_unwind: false,
                supports_simd: true,
                supports_vector: true,
                supports_atomics: true,
                supports_fpu: true,
                supports_dynamic_linking: false,
                supports_static_linking: true,
                supports_shared_libraries: false,
                supports_jit: true,
                supports_aot: true,
                supports_gc: false,
                supports_virtual_memory: false,
                supports_gpu_offload: false,
                supports_async: true,
                supports_debug_info: false,
                features: TargetFeatures::new(),
            },
            _ => Self {
                supports_threads: false,
                supports_tls: false,
                supports_exceptions: false,
                supports_unwind: false,
                supports_simd: false,
                supports_vector: false,
                supports_atomics: false,
                supports_fpu: true,
                supports_dynamic_linking: false,
                supports_static_linking: true,
                supports_shared_libraries: false,
                supports_jit: false,
                supports_aot: true,
                supports_gc: false,
                supports_virtual_memory: false,
                supports_gpu_offload: false,
                supports_async: false,
                supports_debug_info: false,
                features: TargetFeatures::new(),
            },
        }
    }
}
