//! Native Backends and Transpilers
//!
//! Provides helpers for compiling AdeshLang programs to native targets:
//! - `compile_native`: placeholder for direct native compilation
//! - `compile_native_rust`: transpiles Adesh AST into Rust source code
//!
//! The Rust transpiler emits a small dynamic `AdeshValue` runtime and maps
//! language constructs to idiomatic Rust where feasible. It is deterministic
//! and prioritizes readability over maximum performance.
use crate::parsing::ast::{ClassDecl, Expr, ExprKind, Function, Stmt, StmtKind, TokenKind, Value};
use crate::parsing::error::{ErrorKind, LangError};
use crate::parsing::lexer::Lexer;
use crate::parsing::parser::Parser;
use std::fs;
use std::path::Path;

pub fn compile_native(_src: &str, _out: &Path) -> Result<(), LangError> {
    Err(LangError::new(
        ErrorKind::User,
        "native backend not implemented".to_string(),
        0,
        0,
        "".into(),
    ))
}

/// Transpile Adesh source code to Rust
pub fn compile_native_rust(src: &str, out: &Path) -> Result<(), LangError> {
    let mut lx = Lexer::new(src);
    let toks = lx
        .tokenize()
        .map_err(|e| LangError::new(ErrorKind::Lexical, e.to_string(), 0, 0, "".into()))?;
    let mut p = Parser::new(toks, None);
    let prog = p
        .parse_program()
        .map_err(|e| LangError::new(ErrorKind::Parse, e.to_string(), 0, 0, "".into()))?;

    let mut transpiler = RustTranspiler::new();
    let code = transpiler.transpile(&prog);

    fs::write(out, code)
        .map_err(|e| LangError::new(ErrorKind::Io, e.to_string(), 0, 0, "".into()))?;
    Ok(())
}

/// Adesh to Rust transpiler with deterministic type mapping
pub struct RustTranspiler {
    indent: usize,
    classes: Vec<String>,
}

impl RustTranspiler {
    pub fn new() -> Self {
        Self {
            indent: 0,
            classes: Vec::new(),
        }
    }

    /// Transpile a Adesh program to Rust source code
    pub fn transpile(&mut self, stmts: &[Stmt]) -> String {
        let mut code = String::new();

        // Standard imports
        code.push_str("// Auto-generated Rust code from Adesh\n");
        code.push_str("// Generated by adeshlang transpiler\n\n");
        code.push_str("use std::io::Write;\n");
        code.push_str("use std::collections::HashMap;\n");
        code.push_str("use std::rc::Rc;\n");
        code.push_str("use std::cell::RefCell;\n\n");

        // Value enum for dynamic typing
        code.push_str(ADESH_VALUE_ENUM);
        code.push('\n');

        // Helper functions
        code.push_str(ADESH_HELPERS);
        code.push('\n');

        // First pass: collect class definitions
        for stmt in stmts {
            if let StmtKind::Class(cd, _) = &stmt.kind {
                self.classes.push(cd.name.clone());
            }
        }

        // Generate class structs
        for stmt in stmts {
            if let StmtKind::Class(cd, _) = &stmt.kind {
                code.push_str(&self.transpile_class(cd));
                code.push('\n');
            }
        }

        // Main function
        code.push_str("fn main() {\n");
        self.indent = 1;

        // Transpile non-class statements
        for stmt in stmts {
            match &stmt.kind {
                StmtKind::Class(_, _) => {} // Already handled
                StmtKind::Function(f, _) => {
                    // Top-level functions as closures
                    code.push_str(&self.transpile_function_as_closure(f));
                }
                _ => {
                    code.push_str(&self.transpile_stmt(stmt));
                }
            }
        }

        self.indent = 0;
        code.push_str("}\n");

        code
    }

    fn indent_str(&self) -> String {
        "    ".repeat(self.indent)
    }

    fn transpile_class(&self, cd: &ClassDecl) -> String {
        let mut code = String::new();

        // Struct definition
        code.push_str("#[derive(Clone, Debug)]\n");
        code.push_str(&format!("struct {} {{\n", cd.name));
        code.push_str("    _fields: HashMap<String, AdeshValue>,\n");
        code.push_str("}\n\n");

        // Implementation
        code.push_str(&format!("impl {} {{\n", cd.name));

        // Constructor
        code.push_str("    fn new() -> Self {\n");
        code.push_str("        Self {\n");
        code.push_str("            _fields: HashMap::new(),\n");
        code.push_str("        }\n");
        code.push_str("    }\n\n");

        // Methods
        for method in &cd.methods {
            code.push_str(&self.transpile_method(method));
        }

        code.push_str("}\n");

        code
    }

    fn transpile_method(&self, f: &Function) -> String {
        let mut code = String::new();

        // Method signature
        let params: Vec<String> = f
            .params
            .iter()
            .map(|(name, _, _)| format!("{}: AdeshValue", name))
            .collect();

        let params_str = if params.is_empty() {
            "&mut self".to_string()
        } else {
            format!("&mut self, {}", params.join(", "))
        };

        code.push_str(&format!(
            "    fn {}({}) -> AdeshValue {{\n",
            f.name, params_str
        ));

        // Method body
        for stmt in f.body.iter() {
            code.push_str(&self.transpile_stmt_with_indent(stmt, 2));
        }

        code.push_str("        AdeshValue::Null\n");
        code.push_str("    }\n\n");

        code
    }

    fn transpile_function_as_closure(&self, f: &Function) -> String {
        let mut code = String::new();
        let indent = self.indent_str();

        let params: Vec<String> = f
            .params
            .iter()
            .map(|(name, _, _)| format!("{}: AdeshValue", name))
            .collect();

        code.push_str(&format!(
            "{}let {} = |{}| -> AdeshValue {{\n",
            indent,
            f.name,
            params.join(", ")
        ));

        for stmt in f.body.iter() {
            code.push_str(&self.transpile_stmt_with_indent(stmt, self.indent + 1));
        }

        code.push_str(&format!("{}    AdeshValue::Null\n", indent));
        code.push_str(&format!("{}}};\n", indent));

        code
    }

    fn transpile_stmt(&self, stmt: &Stmt) -> String {
        self.transpile_stmt_with_indent(stmt, self.indent)
    }

    fn transpile_stmt_with_indent(&self, stmt: &Stmt, indent: usize) -> String {
        let ind = "    ".repeat(indent);
        let mut code = String::new();

        match &stmt.kind {
            StmtKind::ShareDeclaration(decl, _) => {
                code.push_str(&format!(
                    "{}let mut {}: AdeshValue = {};\n",
                    ind,
                    decl.name,
                    self.transpile_expr(&decl.expr)
                ));
            }
            StmtKind::StrongDeclaration(decl, _) => {
                code.push_str(&format!(
                    "{}let mut {}: AdeshValue = {};\n",
                    ind,
                    decl.name,
                    self.transpile_expr(&decl.expr)
                ));
            }
            StmtKind::WeakDeclaration(decl, _) => {
                code.push_str(&format!(
                    "{}let mut {}: AdeshValue = {};\n",
                    ind,
                    decl.name,
                    self.transpile_expr(&decl.expr)
                ));
            }
            StmtKind::Let(name, init, _, _, is_const, _is_readonly) => {
                let keyword = if *is_const { "let" } else { "let mut" };
                if let Some(expr) = init {
                    code.push_str(&format!(
                        "{}{} {}: AdeshValue = {};\n",
                        ind,
                        keyword,
                        name,
                        self.transpile_expr(expr)
                    ));
                } else {
                    code.push_str(&format!(
                        "{}{} {}: AdeshValue = AdeshValue::Null;\n",
                        ind, keyword, name
                    ));
                }
            }
            StmtKind::ExprStmt(expr) => {
                code.push_str(&format!("{}{};\n", ind, self.transpile_expr(expr)));
            }
            StmtKind::If {
                cond,
                then_branch,
                else_branch,
            } => {
                code.push_str(&format!(
                    "{}if {}.truthy() {{\n",
                    ind,
                    self.transpile_expr(cond)
                ));
                code.push_str(&self.transpile_stmt_with_indent(then_branch, indent + 1));
                if let Some(else_br) = else_branch {
                    code.push_str(&format!("{}}} else {{\n", ind));
                    code.push_str(&self.transpile_stmt_with_indent(else_br, indent + 1));
                }
                code.push_str(&format!("{}}}\n", ind));
            }
            StmtKind::While { cond, body } => {
                code.push_str(&format!(
                    "{}while {}.truthy() {{\n",
                    ind,
                    self.transpile_expr(cond)
                ));
                code.push_str(&self.transpile_stmt_with_indent(body, indent + 1));
                code.push_str(&format!("{}}}\n", ind));
            }
            StmtKind::ForIn { name, iter, body } => {
                code.push_str(&format!(
                    "{}for {} in {}.to_iter() {{\n",
                    ind,
                    name,
                    self.transpile_expr(iter)
                ));
                code.push_str(&self.transpile_stmt_with_indent(body, indent + 1));
                code.push_str(&format!("{}}}\n", ind));
            }
            StmtKind::Return(expr) => {
                if let Some(e) = expr {
                    code.push_str(&format!("{}return {};\n", ind, self.transpile_expr(e)));
                } else {
                    code.push_str(&format!("{}return AdeshValue::Null;\n", ind));
                }
            }
            StmtKind::Block(stmts) => {
                code.push_str(&format!("{}{{\n", ind));
                for s in stmts {
                    code.push_str(&self.transpile_stmt_with_indent(s, indent + 1));
                }
                code.push_str(&format!("{}}}\n", ind));
            }
            StmtKind::Break => {
                code.push_str(&format!("{}break;\n", ind));
            }
            StmtKind::Continue => {
                code.push_str(&format!("{}continue;\n", ind));
            }
            StmtKind::TryCatch {
                try_block,
                err_name,
                catch_block,
            } => {
                code.push_str(&format!("{}// try-catch (simulated)\n", ind));
                code.push_str(&format!(
                    "{}let {} = std::panic::catch_unwind(|| {{\n",
                    ind, err_name
                ));
                code.push_str(&self.transpile_stmt_with_indent(try_block, indent + 1));
                code.push_str(&format!("{}}});\n", ind));
                code.push_str(&format!("{}if {}.is_err() {{\n", ind, err_name));
                code.push_str(&self.transpile_stmt_with_indent(catch_block, indent + 1));
                code.push_str(&format!("{}}}\n", ind));
            }
            _ => {
                code.push_str(&format!("{}// unsupported statement\n", ind));
            }
        }

        code
    }

    fn transpile_expr(&self, expr: &Expr) -> String {
        match &expr.kind {
            ExprKind::Literal(v) => self.transpile_value(v),
            ExprKind::Variable(name) => {
                if name == "this" || name == "self" {
                    "self".to_string()
                } else {
                    format!("{}.clone()", name)
                }
            }
            ExprKind::Binary(left, op, right) => {
                let l = self.transpile_expr(left);
                let r = self.transpile_expr(right);
                match op {
                    TokenKind::Plus => format!("adesh_add(&{}, &{})", l, r),
                    TokenKind::Minus => format!("adesh_sub(&{}, &{})", l, r),
                    TokenKind::Star => format!("adesh_mul(&{}, &{})", l, r),
                    TokenKind::Slash => format!("adesh_div(&{}, &{})", l, r),
                    TokenKind::Percent => format!("adesh_mod(&{}, &{})", l, r),
                    TokenKind::EqualEqual => format!("AdeshValue::Bool(adesh_eq(&{}, &{}))", l, r),
                    TokenKind::BangEqual => format!("AdeshValue::Bool(!adesh_eq(&{}, &{}))", l, r),
                    TokenKind::Less => format!("AdeshValue::Bool(adesh_lt(&{}, &{}))", l, r),
                    TokenKind::LessEqual => format!("AdeshValue::Bool(adesh_lte(&{}, &{}))", l, r),
                    TokenKind::Greater => format!("AdeshValue::Bool(adesh_gt(&{}, &{}))", l, r),
                    TokenKind::GreaterEqual => {
                        format!("AdeshValue::Bool(adesh_gte(&{}, &{}))", l, r)
                    }
                    _ => "/* unsupported op */ AdeshValue::Null".to_string(),
                }
            }
            ExprKind::Logical(left, op, right) => {
                let l = self.transpile_expr(left);
                let r = self.transpile_expr(right);
                match op {
                    TokenKind::And => format!("if {}.truthy() {{ {} }} else {{ {} }}", l, r, l),
                    TokenKind::Or => format!("if {}.truthy() {{ {} }} else {{ {} }}", l, l, r),
                    _ => "AdeshValue::Null".to_string(),
                }
            }
            ExprKind::Unary(op, right) => {
                let r = self.transpile_expr(right);
                match op {
                    TokenKind::Minus => format!("adesh_neg(&{})", r),
                    TokenKind::Bang => format!("AdeshValue::Bool(!{}.truthy())", r),
                    _ => "/* unsupported unary */ AdeshValue::Null".to_string(),
                }
            }
            ExprKind::Call(callee, args, _) => {
                let callee_str = self.transpile_expr(callee);
                let args_str: Vec<String> = args.iter().map(|a| self.transpile_expr(a)).collect();

                // Handle print and println specially
                if let ExprKind::Variable(name) = &callee.kind {
                    if name == "print" {
                        return self.transpile_print_call(args);
                    }
                    if name == "println" {
                        return self.transpile_println_call(args);
                    }
                }

                format!("{}({})", callee_str, args_str.join(", "))
            }
            ExprKind::Get(obj, prop) => {
                let o = self.transpile_expr(obj);
                format!("{}.get_prop(\"{}\")", o, prop)
            }
            ExprKind::Set(obj, prop, val) => {
                let o = self.transpile_expr(obj);
                let v = self.transpile_expr(val);
                format!("{}.set_prop(\"{}\", {})", o, prop, v)
            }
            ExprKind::Index(obj, idx) => {
                let o = self.transpile_expr(obj);
                let i = self.transpile_expr(idx);
                format!("{}.index(&{})", o, i)
            }
            ExprKind::Array(items) => {
                let items_str: Vec<String> = items.iter().map(|i| self.transpile_expr(i)).collect();
                format!("AdeshValue::Array(vec![{}])", items_str.join(", "))
            }
            ExprKind::Object(fields) => {
                let fields_str: Vec<String> = fields
                    .iter()
                    .map(|(k, v)| format!("(\"{}\".to_string(), {})", k, self.transpile_expr(v)))
                    .collect();
                format!(
                    "AdeshValue::Object(HashMap::from([{}]))",
                    fields_str.join(", ")
                )
            }
            ExprKind::Tuple(items) => {
                let items_str: Vec<String> = items.iter().map(|i| self.transpile_expr(i)).collect();
                format!("AdeshValue::Tuple(vec![{}])", items_str.join(", "))
            }
            ExprKind::Assign(name, val) => {
                let v = self.transpile_expr(val);
                format!("{{ {} = {}; {}.clone() }}", name, v, name)
            }
            ExprKind::New(ctor, args) => {
                if let ExprKind::Variable(class_name) = &ctor.kind {
                    let args_str: Vec<String> =
                        args.iter().map(|a| self.transpile_expr(a)).collect();
                    if self.classes.contains(class_name) {
                        format!("{}::new(/* {} */)", class_name, args_str.join(", "))
                    } else {
                        format!("AdeshValue::Null /* new {} */", class_name)
                    }
                } else {
                    "AdeshValue::Null".to_string()
                }
            }
            ExprKind::Grouping(inner) => {
                format!("({})", self.transpile_expr(inner))
            }
            ExprKind::Conditional(cond, then_expr, else_expr) => {
                let c = self.transpile_expr(cond);
                let t = self.transpile_expr(then_expr);
                let e = self.transpile_expr(else_expr);
                format!("if {}.truthy() {{ {} }} else {{ {} }}", c, t, e)
            }
            _ => "AdeshValue::Null /* unsupported expr */".to_string(),
        }
    }

    fn transpile_value(&self, v: &Value) -> String {
        match v {
            Value::Number(n) => format!("AdeshValue::Number({}_f64)", n),
            Value::Str(s) => format!("AdeshValue::Str(\"{}\".to_string())", escape_rust_string(s)),
            Value::Bool(b) => format!("AdeshValue::Bool({})", b),
            Value::Null => "AdeshValue::Null".to_string(),
            Value::Char(c) => format!("AdeshValue::Char('{}')", escape_rust_char(*c)),
            // Fixed-width unsigned integer types
            Value::U8(n) => format!("AdeshValue::U8({})", n),
            Value::U16(n) => format!("AdeshValue::U16({})", n),
            Value::U32(n) => format!("AdeshValue::U32({})", n),
            Value::U64(n) => format!("AdeshValue::U64({})", n),
            Value::U128(n) => format!("AdeshValue::U128({})", n),
            // Fixed-width signed integer types
            Value::I8(n) => format!("AdeshValue::I8({})", n),
            Value::I16(n) => format!("AdeshValue::I16({})", n),
            Value::I32(n) => format!("AdeshValue::I32({})", n),
            Value::I64(n) => format!("AdeshValue::I64({})", n),
            Value::I128(n) => format!("AdeshValue::I128({})", n),
            // Fixed-width float types
            Value::F32(n) => format!("AdeshValue::F32({}_f32)", n),
            Value::F64(n) => format!("AdeshValue::F64({}_f64)", n),
            // BigInt
            Value::BigInt(bi) => format!("AdeshValue::BigInt({})", bi),
            // Complex numbers
            Value::Complex(r, i) => format!("AdeshValue::Complex({}_f64, {}_f64)", r, i),
            // Arrays
            Value::Array(items) => {
                let items_str: Vec<String> =
                    items.iter().map(|i| self.transpile_value(i)).collect();
                format!("AdeshValue::Array(vec![{}])", items_str.join(", "))
            }
            // Tuples
            Value::Tuple(items) => {
                let items_str: Vec<String> =
                    items.iter().map(|i| self.transpile_value(i)).collect();
                format!("AdeshValue::Tuple(vec![{}])", items_str.join(", "))
            }
            _ => "AdeshValue::Null".to_string(),
        }
    }

    fn transpile_print_call(&self, args: &[Expr]) -> String {
        format!(
            "adesh_print(&[{}])",
            args.iter()
                .map(|a| format!("&{}", self.transpile_expr(a)))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }

    fn transpile_println_call(&self, args: &[Expr]) -> String {
        format!(
            "adesh_println(&[{}])",
            args.iter()
                .map(|a| format!("&{}", self.transpile_expr(a)))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

/// Escape a string for Rust string literal
fn escape_rust_string(s: &str) -> String {
    let mut result = String::new();
    for c in s.chars() {
        match c {
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            '\0' => result.push_str("\\0"),
            c if c.is_control() => {
                result.push_str(&format!("\\u{{{:x}}}", c as u32));
            }
            _ => result.push(c),
        }
    }
    result
}

/// Escape a character for Rust char literal
fn escape_rust_char(c: char) -> String {
    match c {
        '\\' => "\\\\".to_string(),
        '\'' => "\\'".to_string(),
        '\n' => "\\n".to_string(),
        '\r' => "\\r".to_string(),
        '\t' => "\\t".to_string(),
        '\0' => "\\0".to_string(),
        c if c.is_control() => format!("\\u{{{:x}}}", c as u32),
        _ => c.to_string(),
    }
}

/// Adesh type mapping to Rust types
pub fn map_adesh_type_to_rust(adesh_type: &str) -> &'static str {
    match adesh_type {
        "string" | "str" => "String",
        "bool" | "boolean" => "bool",
        "char" => "char",
        "object" | "dict" => "HashMap<String, AdeshValue>",
        "tuple" => "Vec<AdeshValue>",
        "null" | "void" => "()",
        "any" => "AdeshValue",
        // Fixed-width unsigned integer types
        "u8" => "u8",
        "u16" => "u16",
        "u32" => "u32",
        "u64" => "u64",
        "u128" => "u128",
        // Fixed-width signed integer types
        "i8" => "i8",
        "i16" => "i16",
        "i32" => "i32",
        "i64" => "i64",
        "i128" => "i128",
        // Fixed-width float types
        "f32" => "f32",
        "f64" => "f64",
        // BigInt
        "bigint" => "i128",
        // Complex
        "complex" => "(f64, f64)",
        _ => "AdeshValue",
    }
}

// Adesh Value enum for dynamic typing in generated Rust code
const ADESH_VALUE_ENUM: &str = r#"
#[derive(Clone, Debug)]
enum AdeshValue {
    Null,
    Bool(bool),
    Number(f64),
    Str(String),
    Char(char),
    Array(Vec<AdeshValue>),
    Tuple(Vec<AdeshValue>),
    Object(HashMap<String, AdeshValue>),
    // Fixed-width integer types (unsigned)
    U8(u8),
    U16(u16),
    U32(u32),
    U64(u64),
    U128(u128),
    // Fixed-width integer types (signed)
    I8(i8),
    I16(i16),
    I32(i32),
    I64(i64),
    I128(i128),
    // Fixed-width float types
    F32(f32),
    F64(f64),
    // BigInt (using i128 as approximation)
    BigInt(i128),
    // Complex numbers
    Complex(f64, f64),
}

impl AdeshValue {
    fn truthy(&self) -> bool {
        match self {
            AdeshValue::Null => false,
            AdeshValue::Bool(b) => *b,
            AdeshValue::Number(n) => *n != 0.0,
            AdeshValue::Str(s) => !s.is_empty(),
            AdeshValue::Array(a) => !a.is_empty(),
            AdeshValue::U8(n) => *n != 0,
            AdeshValue::U16(n) => *n != 0,
            AdeshValue::U32(n) => *n != 0,
            AdeshValue::U64(n) => *n != 0,
            AdeshValue::U128(n) => *n != 0,
            AdeshValue::I8(n) => *n != 0,
            AdeshValue::I16(n) => *n != 0,
            AdeshValue::I32(n) => *n != 0,
            AdeshValue::I64(n) => *n != 0,
            AdeshValue::I128(n) => *n != 0,
            AdeshValue::F32(n) => *n != 0.0,
            AdeshValue::F64(n) => *n != 0.0,
            AdeshValue::BigInt(n) => *n != 0,
            AdeshValue::Complex(r, i) => *r != 0.0 || *i != 0.0,
            _ => true,
        }
    }
    
    fn to_iter(&self) -> Vec<AdeshValue> {
        match self {
            AdeshValue::Array(a) => a.clone(),
            AdeshValue::Str(s) => s.chars().map(|c| AdeshValue::Char(c)).collect(),
            _ => vec![],
        }
    }
    
    fn get_prop(&self, key: &str) -> AdeshValue {
        match self {
            AdeshValue::Object(m) => m.get(key).cloned().unwrap_or(AdeshValue::Null),
            AdeshValue::Array(a) => {
                if let Ok(i) = key.parse::<usize>() {
                    a.get(i).cloned().unwrap_or(AdeshValue::Null)
                } else if key == "length" || key == "len" {
                    AdeshValue::Number(a.len() as f64)
                } else {
                    AdeshValue::Null
                }
            }
            AdeshValue::Str(s) => {
                if key == "length" || key == "len" {
                    AdeshValue::Number(s.len() as f64)
                } else {
                    AdeshValue::Null
                }
            }
            _ => AdeshValue::Null,
        }
    }
    
    fn index(&self, idx: &AdeshValue) -> AdeshValue {
        match (self, idx) {
            (AdeshValue::Array(a), AdeshValue::Number(n)) => {
                a.get(*n as usize).cloned().unwrap_or(AdeshValue::Null)
            }
            (AdeshValue::Object(m), AdeshValue::Str(k)) => {
                m.get(k).cloned().unwrap_or(AdeshValue::Null)
            }
            (AdeshValue::Str(s), AdeshValue::Number(n)) => {
                s.chars().nth(*n as usize).map(AdeshValue::Char).unwrap_or(AdeshValue::Null)
            }
            _ => AdeshValue::Null,
        }
    }
    
    fn to_number(&self) -> f64 {
        match self {
            AdeshValue::Number(n) => *n,
            AdeshValue::U8(n) => *n as f64,
            AdeshValue::U16(n) => *n as f64,
            AdeshValue::U32(n) => *n as f64,
            AdeshValue::U64(n) => *n as f64,
            AdeshValue::U128(n) => *n as f64,
            AdeshValue::I8(n) => *n as f64,
            AdeshValue::I16(n) => *n as f64,
            AdeshValue::I32(n) => *n as f64,
            AdeshValue::I64(n) => *n as f64,
            AdeshValue::I128(n) => *n as f64,
            AdeshValue::F32(n) => *n as f64,
            AdeshValue::F64(n) => *n,
            AdeshValue::BigInt(n) => *n as f64,
            AdeshValue::Bool(b) => if *b { 1.0 } else { 0.0 },
            _ => 0.0,
        }
    }
}

impl std::fmt::Display for AdeshValue {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AdeshValue::Null => write!(f, "null"),
            AdeshValue::Bool(b) => write!(f, "{}", b),
            AdeshValue::Number(n) => write!(f, "{}", n),
            AdeshValue::Str(s) => write!(f, "{}", s),
            AdeshValue::Char(c) => write!(f, "{}", c),
            AdeshValue::Array(a) => {
                let items: Vec<String> = a.iter().map(|v| format!("{}", v)).collect();
                write!(f, "[{}]", items.join(", "))
            }
            AdeshValue::Tuple(t) => {
                let items: Vec<String> = t.iter().map(|v| format!("{}", v)).collect();
                write!(f, "({})", items.join(", "))
            }
            AdeshValue::Object(m) => {
                let items: Vec<String> = m.iter().map(|(k, v)| format!("{}: {}", k, v)).collect();
                write!(f, "{{{}}}", items.join(", "))
            }
            AdeshValue::U8(n) => write!(f, "{}", n),
            AdeshValue::U16(n) => write!(f, "{}", n),
            AdeshValue::U32(n) => write!(f, "{}", n),
            AdeshValue::U64(n) => write!(f, "{}", n),
            AdeshValue::U128(n) => write!(f, "{}", n),
            AdeshValue::I8(n) => write!(f, "{}", n),
            AdeshValue::I16(n) => write!(f, "{}", n),
            AdeshValue::I32(n) => write!(f, "{}", n),
            AdeshValue::I64(n) => write!(f, "{}", n),
            AdeshValue::I128(n) => write!(f, "{}", n),
            AdeshValue::F32(n) => write!(f, "{}", n),
            AdeshValue::F64(n) => write!(f, "{}", n),
            AdeshValue::BigInt(n) => write!(f, "{}n", n),
            AdeshValue::Complex(r, i) => write!(f, "{}+{}i", r, i),
        }
    }
}
"#;

// Helper functions for Adesh operations
const ADESH_HELPERS: &str = r#"
fn adesh_pretty_format(value: &AdeshValue, indent: usize) -> String {
    let indent_str = "  ".repeat(indent);
    let next_indent_str = "  ".repeat(indent + 1);
    
    match value {
        AdeshValue::Null => "null".to_string(),
        AdeshValue::Bool(b) => b.to_string(),
        AdeshValue::Number(n) => n.to_string(),
        AdeshValue::Str(s) => format!("\"{}\"", s),
        AdeshValue::Char(c) => format!("'{}'", c),
        AdeshValue::Array(a) => {
            if a.is_empty() {
                "[]".to_string()
            } else {
                let items: Vec<String> = a.iter()
                    .map(|v| format!("{}{}", next_indent_str, adesh_pretty_format(v, indent + 1)))
                    .collect();
                format!("[\n{}\n{}]", items.join(",\n"), indent_str)
            }
        }
        AdeshValue::Tuple(t) => {
            if t.is_empty() {
                "()".to_string()
            } else {
                let items: Vec<String> = t.iter()
                    .map(|v| format!("{}{}", next_indent_str, adesh_pretty_format(v, indent + 1)))
                    .collect();
                format!("(\n{}\n{})", items.join(",\n"), indent_str)
            }
        }
        AdeshValue::Object(m) => {
            if m.is_empty() {
                "{}".to_string()
            } else {
                let mut keys: Vec<&String> = m.keys().collect();
                keys.sort();
                let items: Vec<String> = keys.iter()
                    .map(|k| {
                        let v = m.get(*k).unwrap();
                        format!("{}{}: {}", next_indent_str, k, adesh_pretty_format(v, indent + 1))
                    })
                    .collect();
                format!("{{\n{}\n{}}}", items.join(",\n"), indent_str)
            }
        }
        _ => format!("{}", value),
    }
}

fn adesh_print(args: &[&AdeshValue]) {
    use std::io::{self, Write};
    
    // Check if the last arg is an options object
    let (values, options) = if args.len() > 0 {
        if let AdeshValue::Object(opts) = args[args.len() - 1] {
            // Check if it has any print-related options (pretty, sep, end, etc.)
            if opts.contains_key("pretty") || opts.contains_key("sep") || opts.contains_key("end") {
                (&args[..args.len() - 1], Some(opts))
            } else {
                (args, None)
            }
        } else {
            (args, None)
        }
    } else {
        (args, None)
    };
    
    // Get options or use defaults
    let sep = options
        .and_then(|o| o.get("sep"))
        .and_then(|v| if let AdeshValue::Str(s) = v { Some(s.as_str()) } else { None })
        .unwrap_or(" ");
    let end = options
        .and_then(|o| o.get("end"))
        .and_then(|v| if let AdeshValue::Str(s) = v { Some(s.as_str()) } else { None })
        .unwrap_or("\n");
    let pretty = options
        .and_then(|o| o.get("pretty"))
        .and_then(|v| match v {
            AdeshValue::Bool(true) =>Some(true),
            _ => None,
        })
        .unwrap_or(false);
    
    // Format and print values
    if pretty {
        let output: Vec<String> = values.iter().map(|v| adesh_pretty_format(v, 0)).collect();
        print!("{}{}", output.join(sep), end);
    } else {
        let output: Vec<String> = values.iter().map(|v| format!("{}", v)).collect();
        print!("{}{}", output.join(sep), end);
    }
    let _ = io::stdout().flush();
}

fn adesh_println(args: &[&AdeshValue]) {
    let output: Vec<String> = args.iter().map(|v| format!("{}", v)).collect();
    println!("{}", output.join(" "));
}

fn adesh_add(a: &AdeshValue, b: &AdeshValue) -> AdeshValue {
    match (a, b) {
        (AdeshValue::Number(x), AdeshValue::Number(y)) => AdeshValue::Number(x + y),
        (AdeshValue::Str(x), AdeshValue::Str(y)) => AdeshValue::Str(format!("{}{}", x, y)),
        (AdeshValue::Str(x), y) => AdeshValue::Str(format!("{}{}", x, y)),
        (x, AdeshValue::Str(y)) => AdeshValue::Str(format!("{}{}", x, y)),
        (AdeshValue::Array(x), AdeshValue::Array(y)) => {
            let mut result = x.clone();
            result.extend(y.clone());
            AdeshValue::Array(result)
        }
        // Fixed-width integer arithmetic
        (AdeshValue::U8(x), AdeshValue::U8(y)) => AdeshValue::U8(x.wrapping_add(*y)),
        (AdeshValue::U16(x), AdeshValue::U16(y)) => AdeshValue::U16(x.wrapping_add(*y)),
        (AdeshValue::U32(x), AdeshValue::U32(y)) => AdeshValue::U32(x.wrapping_add(*y)),
        (AdeshValue::U64(x), AdeshValue::U64(y)) => AdeshValue::U64(x.wrapping_add(*y)),
        (AdeshValue::U128(x), AdeshValue::U128(y)) => AdeshValue::U128(x.wrapping_add(*y)),
        (AdeshValue::I8(x), AdeshValue::I8(y)) => AdeshValue::I8(x.wrapping_add(*y)),
        (AdeshValue::I16(x), AdeshValue::I16(y)) => AdeshValue::I16(x.wrapping_add(*y)),
        (AdeshValue::I32(x), AdeshValue::I32(y)) => AdeshValue::I32(x.wrapping_add(*y)),
        (AdeshValue::I64(x), AdeshValue::I64(y)) => AdeshValue::I64(x.wrapping_add(*y)),
        (AdeshValue::I128(x), AdeshValue::I128(y)) => AdeshValue::I128(x.wrapping_add(*y)),
        (AdeshValue::F32(x), AdeshValue::F32(y)) => AdeshValue::F32(x + y),
        (AdeshValue::F64(x), AdeshValue::F64(y)) => AdeshValue::F64(x + y),
        (AdeshValue::BigInt(x), AdeshValue::BigInt(y)) => AdeshValue::BigInt(x.wrapping_add(*y)),
        // Cross-type to Number
        _ => AdeshValue::Number(a.to_number() + b.to_number()),
    }
}

fn adesh_sub(a: &AdeshValue, b: &AdeshValue) -> AdeshValue {
    match (a, b) {
        (AdeshValue::Number(x), AdeshValue::Number(y)) => AdeshValue::Number(x - y),
        (AdeshValue::U8(x), AdeshValue::U8(y)) => AdeshValue::U8(x.wrapping_sub(*y)),
        (AdeshValue::U16(x), AdeshValue::U16(y)) => AdeshValue::U16(x.wrapping_sub(*y)),
        (AdeshValue::U32(x), AdeshValue::U32(y)) => AdeshValue::U32(x.wrapping_sub(*y)),
        (AdeshValue::U64(x), AdeshValue::U64(y)) => AdeshValue::U64(x.wrapping_sub(*y)),
        (AdeshValue::U128(x), AdeshValue::U128(y)) => AdeshValue::U128(x.wrapping_sub(*y)),
        (AdeshValue::I8(x), AdeshValue::I8(y)) => AdeshValue::I8(x.wrapping_sub(*y)),
        (AdeshValue::I16(x), AdeshValue::I16(y)) => AdeshValue::I16(x.wrapping_sub(*y)),
        (AdeshValue::I32(x), AdeshValue::I32(y)) => AdeshValue::I32(x.wrapping_sub(*y)),
        (AdeshValue::I64(x), AdeshValue::I64(y)) => AdeshValue::I64(x.wrapping_sub(*y)),
        (AdeshValue::I128(x), AdeshValue::I128(y)) => AdeshValue::I128(x.wrapping_sub(*y)),
        (AdeshValue::F32(x), AdeshValue::F32(y)) => AdeshValue::F32(x - y),
        (AdeshValue::F64(x), AdeshValue::F64(y)) => AdeshValue::F64(x - y),
        (AdeshValue::BigInt(x), AdeshValue::BigInt(y)) => AdeshValue::BigInt(x.wrapping_sub(*y)),
        _ => AdeshValue::Number(a.to_number() - b.to_number()),
    }
}

fn adesh_mul(a: &AdeshValue, b: &AdeshValue) -> AdeshValue {
    match (a, b) {
        (AdeshValue::Number(x), AdeshValue::Number(y)) => AdeshValue::Number(x * y),
        (AdeshValue::U8(x), AdeshValue::U8(y)) => AdeshValue::U8(x.wrapping_mul(*y)),
        (AdeshValue::U16(x), AdeshValue::U16(y)) => AdeshValue::U16(x.wrapping_mul(*y)),
        (AdeshValue::U32(x), AdeshValue::U32(y)) => AdeshValue::U32(x.wrapping_mul(*y)),
        (AdeshValue::U64(x), AdeshValue::U64(y)) => AdeshValue::U64(x.wrapping_mul(*y)),
        (AdeshValue::U128(x), AdeshValue::U128(y)) => AdeshValue::U128(x.wrapping_mul(*y)),
        (AdeshValue::I8(x), AdeshValue::I8(y)) => AdeshValue::I8(x.wrapping_mul(*y)),
        (AdeshValue::I16(x), AdeshValue::I16(y)) => AdeshValue::I16(x.wrapping_mul(*y)),
        (AdeshValue::I32(x), AdeshValue::I32(y)) => AdeshValue::I32(x.wrapping_mul(*y)),
        (AdeshValue::I64(x), AdeshValue::I64(y)) => AdeshValue::I64(x.wrapping_mul(*y)),
        (AdeshValue::I128(x), AdeshValue::I128(y)) => AdeshValue::I128(x.wrapping_mul(*y)),
        (AdeshValue::F32(x), AdeshValue::F32(y)) => AdeshValue::F32(x * y),
        (AdeshValue::F64(x), AdeshValue::F64(y)) => AdeshValue::F64(x * y),
        (AdeshValue::BigInt(x), AdeshValue::BigInt(y)) => AdeshValue::BigInt(x.wrapping_mul(*y)),
        _ => AdeshValue::Number(a.to_number() * b.to_number()),
    }
}

fn adesh_div(a: &AdeshValue, b: &AdeshValue) -> AdeshValue {
    match (a, b) {
        (AdeshValue::Number(x), AdeshValue::Number(y)) => AdeshValue::Number(x / y),
        (AdeshValue::U8(x), AdeshValue::U8(y)) if *y != 0 => AdeshValue::U8(x / y),
        (AdeshValue::U16(x), AdeshValue::U16(y)) if *y != 0 => AdeshValue::U16(x / y),
        (AdeshValue::U32(x), AdeshValue::U32(y)) if *y != 0 => AdeshValue::U32(x / y),
        (AdeshValue::U64(x), AdeshValue::U64(y)) if *y != 0 => AdeshValue::U64(x / y),
        (AdeshValue::U128(x), AdeshValue::U128(y)) if *y != 0 => AdeshValue::U128(x / y),
        (AdeshValue::I8(x), AdeshValue::I8(y)) if *y != 0 => AdeshValue::I8(x / y),
        (AdeshValue::I16(x), AdeshValue::I16(y)) if *y != 0 => AdeshValue::I16(x / y),
        (AdeshValue::I32(x), AdeshValue::I32(y)) if *y != 0 => AdeshValue::I32(x / y),
        (AdeshValue::I64(x), AdeshValue::I64(y)) if *y != 0 => AdeshValue::I64(x / y),
        (AdeshValue::I128(x), AdeshValue::I128(y)) if *y != 0 => AdeshValue::I128(x / y),
        (AdeshValue::F32(x), AdeshValue::F32(y)) => AdeshValue::F32(x / y),
        (AdeshValue::F64(x), AdeshValue::F64(y)) => AdeshValue::F64(x / y),
        (AdeshValue::BigInt(x), AdeshValue::BigInt(y)) if *y != 0 => AdeshValue::BigInt(x / y),
        _ => AdeshValue::Number(a.to_number() / b.to_number()),
    }
}

fn adesh_mod(a: &AdeshValue, b: &AdeshValue) -> AdeshValue {
    match (a, b) {
        (AdeshValue::Number(x), AdeshValue::Number(y)) => AdeshValue::Number(x % y),
        (AdeshValue::U8(x), AdeshValue::U8(y)) if *y != 0 => AdeshValue::U8(x % y),
        (AdeshValue::U16(x), AdeshValue::U16(y)) if *y != 0 => AdeshValue::U16(x % y),
        (AdeshValue::U32(x), AdeshValue::U32(y)) if *y != 0 => AdeshValue::U32(x % y),
        (AdeshValue::U64(x), AdeshValue::U64(y)) if *y != 0 => AdeshValue::U64(x % y),
        (AdeshValue::U128(x), AdeshValue::U128(y)) if *y != 0 => AdeshValue::U128(x % y),
        (AdeshValue::I8(x), AdeshValue::I8(y)) if *y != 0 => AdeshValue::I8(x % y),
        (AdeshValue::I16(x), AdeshValue::I16(y)) if *y != 0 => AdeshValue::I16(x % y),
        (AdeshValue::I32(x), AdeshValue::I32(y)) if *y != 0 => AdeshValue::I32(x % y),
        (AdeshValue::I64(x), AdeshValue::I64(y)) if *y != 0 => AdeshValue::I64(x % y),
        (AdeshValue::I128(x), AdeshValue::I128(y)) if *y != 0 => AdeshValue::I128(x % y),
        (AdeshValue::F32(x), AdeshValue::F32(y)) => AdeshValue::F32(x % y),
        (AdeshValue::F64(x), AdeshValue::F64(y)) => AdeshValue::F64(x % y),
        (AdeshValue::BigInt(x), AdeshValue::BigInt(y)) if *y != 0 => AdeshValue::BigInt(x % y),
        _ => AdeshValue::Number(a.to_number() % b.to_number()),
    }
}

fn adesh_neg(a: &AdeshValue) -> AdeshValue {
    match a {
        AdeshValue::Number(x) => AdeshValue::Number(-x),
        AdeshValue::I8(x) => AdeshValue::I8(x.wrapping_neg()),
        AdeshValue::I16(x) => AdeshValue::I16(x.wrapping_neg()),
        AdeshValue::I32(x) => AdeshValue::I32(x.wrapping_neg()),
        AdeshValue::I64(x) => AdeshValue::I64(x.wrapping_neg()),
        AdeshValue::I128(x) => AdeshValue::I128(x.wrapping_neg()),
        AdeshValue::F32(x) => AdeshValue::F32(-x),
        AdeshValue::F64(x) => AdeshValue::F64(-x),
        AdeshValue::BigInt(x) => AdeshValue::BigInt(-x),
        _ => AdeshValue::Number(-a.to_number()),
    }
}

fn adesh_eq(a: &AdeshValue, b: &AdeshValue) -> bool {
    match (a, b) {
        (AdeshValue::Null, AdeshValue::Null) => true,
        (AdeshValue::Bool(x), AdeshValue::Bool(y)) => x == y,
        (AdeshValue::Number(x), AdeshValue::Number(y)) => x == y,
        (AdeshValue::Str(x), AdeshValue::Str(y)) => x == y,
        (AdeshValue::Char(x), AdeshValue::Char(y)) => x == y,
        (AdeshValue::U8(x), AdeshValue::U8(y)) => x == y,
        (AdeshValue::U16(x), AdeshValue::U16(y)) => x == y,
        (AdeshValue::U32(x), AdeshValue::U32(y)) => x == y,
        (AdeshValue::U64(x), AdeshValue::U64(y)) => x == y,
        (AdeshValue::U128(x), AdeshValue::U128(y)) => x == y,
        (AdeshValue::I8(x), AdeshValue::I8(y)) => x == y,
        (AdeshValue::I16(x), AdeshValue::I16(y)) => x == y,
        (AdeshValue::I32(x), AdeshValue::I32(y)) => x == y,
        (AdeshValue::I64(x), AdeshValue::I64(y)) => x == y,
        (AdeshValue::I128(x), AdeshValue::I128(y)) => x == y,
        (AdeshValue::F32(x), AdeshValue::F32(y)) => x == y,
        (AdeshValue::F64(x), AdeshValue::F64(y)) => x == y,
        (AdeshValue::BigInt(x), AdeshValue::BigInt(y)) => x == y,
        _ => a.to_number() == b.to_number(),
    }
}

fn adesh_lt(a: &AdeshValue, b: &AdeshValue) -> bool {
    match (a, b) {
        (AdeshValue::Number(x), AdeshValue::Number(y)) => x < y,
        (AdeshValue::Str(x), AdeshValue::Str(y)) => x < y,
        (AdeshValue::U8(x), AdeshValue::U8(y)) => x < y,
        (AdeshValue::U16(x), AdeshValue::U16(y)) => x < y,
        (AdeshValue::U32(x), AdeshValue::U32(y)) => x < y,
        (AdeshValue::U64(x), AdeshValue::U64(y)) => x < y,
        (AdeshValue::U128(x), AdeshValue::U128(y)) => x < y,
        (AdeshValue::I8(x), AdeshValue::I8(y)) => x < y,
        (AdeshValue::I16(x), AdeshValue::I16(y)) => x < y,
        (AdeshValue::I32(x), AdeshValue::I32(y)) => x < y,
        (AdeshValue::I64(x), AdeshValue::I64(y)) => x < y,
        (AdeshValue::I128(x), AdeshValue::I128(y)) => x < y,
        (AdeshValue::F32(x), AdeshValue::F32(y)) => x < y,
        (AdeshValue::F64(x), AdeshValue::F64(y)) => x < y,
        (AdeshValue::BigInt(x), AdeshValue::BigInt(y)) => x < y,
        _ => a.to_number() < b.to_number(),
    }
}

fn adesh_lte(a: &AdeshValue, b: &AdeshValue) -> bool {
    match (a, b) {
        (AdeshValue::Number(x), AdeshValue::Number(y)) => x <= y,
        (AdeshValue::Str(x), AdeshValue::Str(y)) => x <= y,
        (AdeshValue::U8(x), AdeshValue::U8(y)) => x <= y,
        (AdeshValue::U16(x), AdeshValue::U16(y)) => x <= y,
        (AdeshValue::U32(x), AdeshValue::U32(y)) => x <= y,
        (AdeshValue::U64(x), AdeshValue::U64(y)) => x <= y,
        (AdeshValue::U128(x), AdeshValue::U128(y)) => x <= y,
        (AdeshValue::I8(x), AdeshValue::I8(y)) => x <= y,
        (AdeshValue::I16(x), AdeshValue::I16(y)) => x <= y,
        (AdeshValue::I32(x), AdeshValue::I32(y)) => x <= y,
        (AdeshValue::I64(x), AdeshValue::I64(y)) => x <= y,
        (AdeshValue::I128(x), AdeshValue::I128(y)) => x <= y,
        (AdeshValue::F32(x), AdeshValue::F32(y)) => x <= y,
        (AdeshValue::F64(x), AdeshValue::F64(y)) => x <= y,
        (AdeshValue::BigInt(x), AdeshValue::BigInt(y)) => x <= y,
        _ => a.to_number() <= b.to_number(),
    }
}

fn adesh_gt(a: &AdeshValue, b: &AdeshValue) -> bool {
    match (a, b) {
        (AdeshValue::Number(x), AdeshValue::Number(y)) => x > y,
        (AdeshValue::Str(x), AdeshValue::Str(y)) => x > y,
        (AdeshValue::U8(x), AdeshValue::U8(y)) => x > y,
        (AdeshValue::U16(x), AdeshValue::U16(y)) => x > y,
        (AdeshValue::U32(x), AdeshValue::U32(y)) => x > y,
        (AdeshValue::U64(x), AdeshValue::U64(y)) => x > y,
        (AdeshValue::U128(x), AdeshValue::U128(y)) => x > y,
        (AdeshValue::I8(x), AdeshValue::I8(y)) => x > y,
        (AdeshValue::I16(x), AdeshValue::I16(y)) => x > y,
        (AdeshValue::I32(x), AdeshValue::I32(y)) => x > y,
        (AdeshValue::I64(x), AdeshValue::I64(y)) => x > y,
        (AdeshValue::I128(x), AdeshValue::I128(y)) => x > y,
        (AdeshValue::F32(x), AdeshValue::F32(y)) => x > y,
        (AdeshValue::F64(x), AdeshValue::F64(y)) => x > y,
        (AdeshValue::BigInt(x), AdeshValue::BigInt(y)) => x > y,
        _ => a.to_number() > b.to_number(),
    }
}

fn adesh_gte(a: &AdeshValue, b: &AdeshValue) -> bool {
    match (a, b) {
        (AdeshValue::Number(x), AdeshValue::Number(y)) => x >= y,
        (AdeshValue::Str(x), AdeshValue::Str(y)) => x >= y,
        (AdeshValue::U8(x), AdeshValue::U8(y)) => x >= y,
        (AdeshValue::U16(x), AdeshValue::U16(y)) => x >= y,
        (AdeshValue::U32(x), AdeshValue::U32(y)) => x >= y,
        (AdeshValue::U64(x), AdeshValue::U64(y)) => x >= y,
        (AdeshValue::U128(x), AdeshValue::U128(y)) => x >= y,
        (AdeshValue::I8(x), AdeshValue::I8(y)) => x >= y,
        (AdeshValue::I16(x), AdeshValue::I16(y)) => x >= y,
        (AdeshValue::I32(x), AdeshValue::I32(y)) => x >= y,
        (AdeshValue::I64(x), AdeshValue::I64(y)) => x >= y,
        (AdeshValue::I128(x), AdeshValue::I128(y)) => x >= y,
        (AdeshValue::F32(x), AdeshValue::F32(y)) => x >= y,
        (AdeshValue::F64(x), AdeshValue::F64(y)) => x >= y,
        (AdeshValue::BigInt(x), AdeshValue::BigInt(y)) => x >= y,
        _ => a.to_number() >= b.to_number(),
    }
}
"#;
